version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: django_container
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=ps_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgconf:/etc/postgresql
      - ./pglog:/var/log/postgresql
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local