version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=ps_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - db_django:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: django_container
volumes:
  db_django: